//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aviva.Automation.Framework
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionHandler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionHandler() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aviva.Automation.Framework.ExceptionHandler", typeof(ExceptionHandler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while trying to access the array with an illegal index.
        /// </summary>
        internal static string arrayindexoutofboundsexception {
            get {
                return ResourceManager.GetString("arrayindexoutofboundsexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click could not be properly executed because the target element was obscured in some way.
        /// </summary>
        internal static string elementclickinterceptedexception {
            get {
                return ResourceManager.GetString("elementclickinterceptedexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is not interact-able even though it is available in DOM.
        /// </summary>
        internal static string elementnotinteractableexception {
            get {
                return ResourceManager.GetString("elementnotinteractableexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is not selectable even though it is available in DOM.
        /// </summary>
        internal static string elementnotselectableexception {
            get {
                return ResourceManager.GetString("elementnotselectableexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is not visible even though it is available in DOM.
        /// </summary>
        internal static string elementnotvisibleexception {
            get {
                return ResourceManager.GetString("elementnotvisibleexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a file in the given path.
        /// </summary>
        internal static string filenotfoundexception {
            get {
                return ResourceManager.GetString("filenotfoundexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occurred due to index of some sort (such as to an array, to a string, or to a vector) is out of range.
        /// </summary>
        internal static string indexoutofboundsexception {
            get {
                return ResourceManager.GetString("indexoutofboundsexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when an attempt is made to access an element of an array or collection with an index that is outside its bounds..
        /// </summary>
        internal static string indexoutofrangeexception {
            get {
                return ResourceManager.GetString("indexoutofrangeexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occurred due to failed or interrupted I/O operations.
        /// </summary>
        internal static string ioexception {
            get {
                return ResourceManager.GetString("ioexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while executing the Java-script.
        /// </summary>
        internal static string javascriptexception {
            get {
                return ResourceManager.GetString("javascriptexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the alert in browser.
        /// </summary>
        internal static string noalertpresentexception {
            get {
                return ResourceManager.GetString("noalertpresentexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the requested cookie.
        /// </summary>
        internal static string nosuchcookieexception {
            get {
                return ResourceManager.GetString("nosuchcookieexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the element in DOM.
        /// </summary>
        internal static string nosuchelementexception {
            get {
                return ResourceManager.GetString("nosuchelementexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the frame.
        /// </summary>
        internal static string nosuchframeexception {
            get {
                return ResourceManager.GetString("nosuchframeexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the session to preform selenium actions.
        /// </summary>
        internal static string nosuchsessionexception {
            get {
                return ResourceManager.GetString("nosuchsessionexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a window.
        /// </summary>
        internal static string nosuchwindowexception {
            get {
                return ResourceManager.GetString("nosuchwindowexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while trying to access the call/access the null object.
        /// </summary>
        internal static string nullpointerexception {
            get {
                return ResourceManager.GetString("nullpointerexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a session in selenium.
        /// </summary>
        internal static string sessionnotcreatedexception {
            get {
                return ResourceManager.GetString("sessionnotcreatedexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred due to element is no longer available with DOM.
        /// </summary>
        internal static string staleelementreferenceexception {
            get {
                return ResourceManager.GetString("staleelementreferenceexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the command in given wait time.
        /// </summary>
        internal static string timeoutexception {
            get {
                return ResourceManager.GetString("timeoutexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred due to some unhandled alert.
        /// </summary>
        internal static string unhandledalertexception {
            get {
                return ResourceManager.GetString("unhandledalertexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred in web driver during the run time.
        /// </summary>
        internal static string webdriverexception {
            get {
                return ResourceManager.GetString("webdriverexception", resourceCulture);
            }
        }
    }
}
